resolver: lts-24.12

packages:
- .
- ../fractalstream-core
- ../fractalstream-backend-llvm

extra-deps:

- git: https://github.com/matt-noonan/cabal-macosx.git
  commit: 7e892fbeb761f4adb29d52b5377e6a1869faf48d

- git: https://github.com/matt-noonan/llvm-hs.git
  commit: 530205d7d85882348a04c1c5422ba5e6af7b7d45
  subdirs:
    - llvm-hs
    - llvm-hs-pure

- git: https://github.com/mgrabmueller/disassembler
  commit: 15a15db1fba50fd0ce52f26f43550fbad5529bf8

- git: https://codeberg.org/wxHaskell/wxHaskell.git
  commit: 5ce677420cbc49bc810ee075922732ed0f3e838c
  subdirs:
    - wx
    - wxcore
    - wxdirect

# Override default flag values for local packages and extra-deps
flags:
  llvm-hs:
    shared-llvm: true

ghc-options:
  llvm-hs:
    -optcxx=-std=c++17

allow-newer: true
